### ISSUE TITLE
Use build matrix in GHA

### ISSUE THREAD

**Issue by wojsmol** [joomla/core-translations#68]
Hi
I suggest use [GHA build matrix](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix) where possible - for example in [crowdin v4 dl package translations](https://github.com/joomla/core-translations/blob/main/.github/workflows/crowdin-v4-dl-package-translations.yml). This reduces code duplication. For this workflow we can use matrix in crowdin action like this:
```yml
- name: Crowdin Download ${{ matrix.language-name }}
      uses: crowdin/github-action@1.4.0
      with:
        # Option to specify a path to the configuration file, without / at the beginning
        config: 'Configurations/Crowdin-J4-All.yml'
        # Upload sources to Crowdin
        upload_sources: false
        # Make pull request of Crowdin translations
        download_translations: true
        # Download specific language
        download_language: ${{ matrix.language-code }}
        # Only download translated strings
        skip_untranslated_strings: true
        # Include approved translations only in exported files. 
        # If not combined with --skip-untranslated-strings option, strings without approval are fulfilled with the source language'
        export_only_approved: true
        # The message of the commit
        commit_message: "New ${{ matrix.language-name }} Crowdin translations by Github Action"
```
and in matrix we define 2 arrays.
